source 'https://rubygems.org'

gem 'data_mapper'
gem 'dm-mysql-adapter'
gem 'foreman'
gem 'hex_string'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'redis'
gem 'serialport'
gem 'twitter'
gem 'unicorn'
gem 'unicorn-rails'
